version: '3.4'

services:

  server-bd:
    build: ./server-bd/
    image: luferlux/mc-sbd-students
    environment:
      - MARIADB_ROOT_HOST=%
      - MARIADB_DATABASE=students
      - MARIADB_ROOT_PASSWORD=toor
    ports:
      - "3306:3306"
    restart: on-failure
    command: --default-authentication-plugin=mysql_native_password

  app-consumer:
    build: ./app-consumer/
    image: luferlux/app-consumer
    container_name: app-consumer
    environment:
      - JAVA_OPTS=""
      - KAFKA_BOOSTRAP_SERVER=b-1.kafkamsk.****.c18.kafka.us-east-1.amazonaws.com:9092
      - DATASOURCE_HOST=server-bd
      - DATASOURCE_PORT=3306
      - DATASOURCE_DATABASE=students
      - DATASOURCE_USER=root
      - DATASOURCE_PWD=toor
    depends_on:
      - server-bd
    links:
      - server-bd:db
    ports:
      - "8090:8080"
    restart: on-failure

  app-producer:
    build: ./app-producer/
    image: luferlux/app-producer
    container_name: app-producer
    environment:
      - JAVA_OPTS=""
      - KAFKA_BOOSTRAP_SERVER=b-1.kafkamsk.****.c18.kafka.us-east-1.amazonaws.com:9092
    ports:
      - "8091:8080"
    restart: on-failure